import { loadJson } from './common.js';
import { ROLES } from './scoring.js';
const form=document.querySelector('#builder'), games=document.querySelector('#games'); let roster;
const num=(v)=>Number(v||0);
function playerOptions(){return roster.players.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}
function addGame(){const i=games.children.length; const section=document.createElement('section'); section.className='card game-editor'; section.innerHTML=`<div class="game-head"><h2>Game ${i+1}</h2><button type="button" class="danger remove">Remove</button></div><div class="form-grid"><label>Opponent<input name="opponent" required></label><label>Result<select name="result"><option value="win">Win</option><option value="loss">Loss</option></select></label><label>Duration (minutes)<input name="duration" type="number" min="1" step="0.01" required></label></div><div class="lineups">${ROLES.map(role=>`<fieldset class="player-row"><legend>${role}</legend><label>Player<select name="playerId">${playerOptions()}</select></label><input type="hidden" name="role" value="${role}"><label>Champion<input name="champion" required></label>${['kills','deaths','assists','cs','gold','damage','visionScore'].map(x=>`<label>${x}<input name="${x}" type="number" min="0" required></label>`).join('')}</fieldset>`).join('')}</div>`; section.querySelector('.remove').onclick=()=>section.remove(); games.append(section)}
function slug(s){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function download(obj,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
roster=await loadJson('./data/players.json'); document.querySelector('#add-game').onclick=addGame; addGame();
form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form), id=slug(fd.get('name')); const tournament={id,name:fd.get('name'),date:fd.get('date'),tier:num(fd.get('tier')),placement:num(fd.get('placement')),manualMvp:null,manualInter:null,games:[...games.children].map(section=>{const fields=section.querySelectorAll('input,select');const one=n=>section.querySelector(`[name="${n}"]`).value;return{opponent:one('opponent'),result:one('result'),durationSeconds:Math.round(num(one('duration'))*60),players:[...section.querySelectorAll('.player-row')].map(row=>{const get=n=>row.querySelector(`[name="${n}"]`).value;return{playerId:get('playerId'),role:get('role'),champion:get('champion'),kills:num(get('kills')),deaths:num(get('deaths')),assists:num(get('assists')),cs:num(get('cs')),gold:num(get('gold')),damage:num(get('damage')),visionScore:num(get('visionScore'))}})}})};download(tournament,`${id}.json`);document.querySelector('#manifest-help').textContent=`Add "tournaments/${id}.json" to clash/data/index.json.`}
